<?php
    $this->declareVars(array(
        'jobId'=>'',
        'perIteration'=>'10',
        'total'=>'0',
        'processed'=>'-1',
        'attachView'=>'',
    ));
?>
<div class="brx-job_control" data-view="brx.JobControl" <?php 
if($this->jobId){ 
    printf(' jobId="%s"', $this->jobId);
}
if($this->perIteration){ 
    printf(' perIteration="%d"', $this->perIteration);
}
if($this->total){ 
    printf(' total="%d"', $this->total);
}
if($this->processed){ 
    printf(' processed="%d"', $this->processed);
}
if($this->attachView){ 
    printf(' attachView="%s"', $this->attachView);
}
?>>
    <div class="processor" data-attach-point="boxProgress">
        <div class="progressbar" data-widget="progressbar" data-attach-widget="progressbar">
            <div class="progress_label" data-attach-point="progresslabel">100%</div>
        </div>
        <div data-attach-point="boxButtons" class="box_buttons">
            <button class="button button-small button_start" data-attach-point="buttons.start" data-attach-event="start">Start</button>
            <button class="button button-small button_pause" data-attach-point="buttons.pause" data-attach-event="pause">Pause</button>
            <button class="button button-small button_resume" data-attach-point="buttons.resume" data-attach-event="resume">Resume</button>
            <button class="button button-small button_stop" data-attach-point="buttons.stop" data-attach-event="stop">Stop</button>
            <span class="field_per_iteration" data-attach-point="fields.perIteration">
                <label>Штук за итерацию:</label>
                <input type="text" value="<?php echo $this->perIteration;?>" data-attach-point="inputs.perIteration"/>
            </span>
        </div>
        <div class="progress_spinner brx_single_spinner" data-view="brx.SingleSpinner" data-attach-view="progressSpinner"></div>
        <div class="box_output" data-attach-point="boxOutput">
        </div>
    </div>
    
</div>