<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


$taxonomy = $this->taxonomy?$this->taxonomy:'category';
//$terms = get_terms(array($taxonomy), array(
//    'order_by' => 'name',
//    'order' => 'ASC',
//    'hide_empty' => false,
//    'hierarchical' => true,
//    'fields' => 'all',
//    
//));
      
function brx_TaxonomyPicker_renderTaxonomyOption($term, $taxonomy){
    $children = get_terms($taxonomy, array(
        'orderby'       => 'name', 
        'order'         => 'ASC',
        'hide_empty'    => false, 
        'number'        => '', 
        'fields'        => 'all', 
        'slug'          => '', 
        'parent'         => $term?$term->term_id:0,
        'hierarchical'  => true, 
    ));
    $ul = '';
    if(!is_wp_error($children) && $children && count($children)){
        $ul = ($term?'<ul class="children">':'<ul class="options" attachpoint="optionsList">')."\n";
        foreach($children as $child){
            $ul.= brx_TaxonomyPicker_renderTaxonomyOption($child, $taxonomy);
        }
        $ul.= "</ul>\n";
    }
    if(!$term){
        return $ul;
    }
    $li = sprintf('<li id="li-%s-%d"><input value="%d" type="checkbox" id="cb-%s-%d" /><label for="cb-%s-%d">%s</label>%s</li>'."\n", 
        $taxonomy,
        $term->term_id,
        $term->term_id,
        $taxonomy,
        $term->term_id,
        $taxonomy,
        $term->term_id,
        $term->name,
        $ul
    );
    return $li;
}

if(!function_exists('wp_terms_checklist')){
    require_once 'wp-admin/includes/template.php';
}
if($this->postId && !$this->ids){
    $this->ids = wp_get_post_terms($this->postId, $taxonomy, array("fields" => "ids"));
}
if(!$this->ids){
    $this->ids = array();
}
if(!$this->modal){
    $this->modal = '';
}
?>
<div class="brx-taxonomy_picker" backbone-view="brx.TaxonomyPicker" <?php if($this->attachView):?>attachView="<?php echo $this->attachView?>"<?php endif;?> taxonomy="<?php echo $taxonomy?>" title="<?php echo $this->title;?>" max="<?php echo $this->max?>" forbidLevels="<?php echo $this->forbidLevels;?>" modal="<?php echo $this->modal;?>" <?php HtmlHelper::hidden(false);?>>
    <input attachpoint="hiddenInput" name="<?php echo $taxonomy?>" type="hidden" value="<?php echo join(',', $this->ids);?>"/>
    <ul class="box_selected" attachpoint="boxSelected"></ul>
    <div class="link_select" attachpoint="linkSelect" attachevent="linkSelectClicked">Выбрать</div>
    <div class="clearfloat"></div>
    <div class="brx-taxonomy_picker-box_options" attachpoint="boxOptions">
        <input class="input_search" type="text" attachpoint="inputSearch" attachevent="keyup: searchOptions"/>
        <div class="nothing_found" attachpoint="boxNothing">Ничего не найдено</div>
        <!--<ul class="options" attachpoint="optionsList">-->
    <?php
        echo brx_TaxonomyPicker_renderTaxonomyOption(null, $taxonomy);
//        wp_terms_checklist(0, $args = array(
//            'descendants_and_self'  => 0,
//            'selected_cats'         => false,
//            'popular_cats'          => false,
//            'walker'                => null,
//            'taxonomy'              => $taxonomy,
//            'checked_ontop'         => false
//        ));
    ?>
        <!--</ul>-->
        <div class="box_links">
            <span class="link link_show_all" attachpoint="linkShowAll" attachevent="showAll">Показать все</span>
            <span class="link link_show_search" attachpoint="linkShowSearch" attachevent="searchOptions">Показать результаты поиска</span>
            <span class="link link_show_selected" attachpoint="linkShowSelected" attachevent="showSelected">Показать выбранные</span>
        </div>
        <div class="button_pane">
            <div class="info">
                <div class="box_count_selected" attachpoint="boxCountSelected">
                    Выбрано: <span attachpoint="viewCountSelected"></span>
                </div>
                <div class="box_count_left" attachpoint="boxCountLeft">
                    Осталось: <span attachpoint="viewCountLeft"></span>
                </div>
                
                
            </div>
            <div class="buttons">
                <button widget="button" attachevent="buttonCancelClicked">Отмена</button>
                <button widget="button" attachevent="buttonOkClicked">Ок</button>
            </div>
        </div>
    </div>
</div>

