<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<div class="brx-ribbon_slider" backbone-view="brx.RibbonSlider" direction="<?php echo $this->direction;?>" <?php 
    foreach($this->htmlAttrs as $key=>$value){printf('%s="%s" ', $key, $this->escape($value));};?>>
    <div class="brx-ribbon_slider-prev" attachPoint="buttonSlidePrev" attachEvent="slidePrev"></div>
    <div class="brx-ribbon_slider-ribbon"  attachPoint="ribbon">
        <div class="brx-ribbon_slider-slider"  attachPoint="slider">
            <?php foreach($this->items as $item):?>
            <div class="brx-ribbon_slider-item">
                <?php echo $item;?>
            </div>
            <?php endforeach;?>
        </div>    
    </div>
    <div class="brx-ribbon_slider-next" attachPoint="buttonSlideNext" attachEvent="slideNext"></div>
    <ol class="brx-ribbon_slider-pages" attachPoint="pagesBox"></ol>
</div>
