<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<div class="brx-ribbon_slider" backbone-view="brx.RibbonSlider" direction="<?php echo $this->direction;?>">
    <div class="brx-ribbon_slider-prev" attachPoint="buttonSlidePrev" attachEvent="slidePrev"></div>
    <div class="brx-ribbon_slider-ribbon"  attachPoint="ribbon">
        <div class="brx-ribbon_slider-slider"  attachPoint="slider">
        </div>    
    </div>
    <div class="brx-ribbon_slider-next" attachPoint="buttonSlideNext" attachEvent="slideNext"></div>
</div>
