<?php
//LessCss::loadLessCss();
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<div class="wrap bem-zf_core-admin">
    <div id="icon-options-general" class="icon32">
        <br/>
    </div>
    <h2>Блокировка сайта</h2>
</div>

<div class="brx-options_form" data-view="brx.OptionsForm" data-scope="site" data-prefix="BlockadeHelper" style="display: none;">
    <div class="form_fields">
        <div class="form_field stretch field_is_blocked" data-attach-point="fields.isBlocked">
            <label class="width35">Блокировка сайта:</label>
            <span class="form_field-input_box">
                <select>
                    <option value="0">Сайт разблокирован</option>
                    <option value="1">Сайт заблокирован</option>
                </select>
            </span>
            <div class="form_field-tips"></div>
        </div>
        <div class="form_field stretch field_title" data-attach-point="fields.title">
            <label class="width25">Заголовок:</label>
            <span class="form_field-input_box">
                <input type="text"/>
            </span>
            <div class="form_field-tips"></div>
        </div>
        <div class="form_field fullsize field_message" data-attach-point="fields.message">
            <label>Сообщение:</label>
            <span class="form_field-input_box">
                <textarea>
                </textarea>
            </span>
            <div class="form_field-tips"></div>
        </div>
    </div>
    <div class="button_pane">
        <button class="button button-large button-primary" data-attach-event="saveOptions">Применить</button>
    </div>
</div>
<?php // WidgetHelper::renderMultiSpinner();?>
<?php // ZF_Core::addJQueryWidgets();?>
