<?php

//LessCss::loadLessCss();


$zfPost = $this->zfPost;

?>
<div class="admin-content_fragment_metabox">
    <div class="form_field field_link_to">
        <label>Link to:</label>
        <span class="form_field-input_box"><input name="content_fragment_link_to" type="text" value="<?php echo $this->escape($this->linkTo); ?>"/></span>
        <div class="form_field-tips"></div>
    </div>
</div>