<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<div class="wrap bem-zf_core-admin">
    <div id="icon-options-general" class="icon32">
        <br/>
    </div>
    <h2>Общие настройки ZF Core</h2>
</div>

<div class="bem-admin_setup_form " backbone-view="brx.OptionsForm" scope="site" prefix="ZfCore" style="display: none;">
    <div class="form_fields">
        <div class="form_field field_beautify_style" attachpoint="fields.uiFramework">
            <label>UI Framework:</label>
            <span class="form_field-input_box">
                <select>
                    <option value="">- None -</option>
                    <option value="jQueryUI">jQueryUI</option>
                    <option value="bootstrap">Twitter Bootstrap</option>
                </select>
            </span>
            <div class="form_field-tips"></div>
        </div>
    </div>
    <div class="button_pane">
        <button widget="button" attachevent="saveOptions">Сохранить</button>
    </div>
</div>
<?php ZF_Core::addJQueryWidgets();?>
