<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<div class="wrap bem-zf_core-admin">
    <div id="icon-options-general" class="icon32">
        <br/>
    </div>
    <h2>Общие настройки ZF Core</h2>
</div>

<div class="bem-admin_setup_form " widget="brx.setupForm" url="/api/zf-setup/update-options" style="display: none;">
    <div class="form_fields">
        <div class="form_field field_template" attachpoint="fields.template">
            <label>Шаблон страницы поиска:</label>
            <span class="form_field-input_box"><input name="template" type="text" value="<?php echo $this->escape($this->emailTemplate); ?>"/></span>
            <div class="form_field-tips"></div>
        </div>
    </div>
    <div class="button_pane">
        <button widget="button" attachevent="saveOptions">Сохранить</button>
    </div>
    <script type="text/javascript">
        window.setupOptions = <?php echo JsonHelper::encode($this->options);?>;
    </script>
</div>
